# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ba394445d74095281356aa579ba4563c6a4cf79887ec859f2f757e7ef09df953c93be74695205098ccf1a70aa88e129c6b4e7e975d29710177d26e2d5df9c2f2

test:
  secret_key_base: d4da430a787f6fcac2fec0b986bddcaa96f7b8f3fe9bcacf13e513ac6b644448d73008d64002ef2f927f7c11975eb6e2b26330bf8fe8dc512d6869821c279ed5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
